### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by zhaopengme** [easy-programming-guide/NOKIA-EA0326GMP#1]
![image](https://github.com/user-attachments/assets/2952a6af-e0db-41c0-bacc-b0df05d0142e)
我刷了固件后，无限重启，只能进入这个界面了。下一步需要怎么处理呢

**Comment by wujun4code** [comment]
@zhaopengme 

1. 下载这个固件 https://github.com/easy-programming-guide/NOKIA-EA0326GMP/blob/main/openwrt-07.23.2024-mediatek-filogic-nokia_ea0326gmp-squashfs-sysupgrade.bin
2. 然后点击 Browse，选择 openwrt-07.23.2024-mediatek-filogic-nokia_ea0326gmp-squashfs-sysupgrade.bin，再点击 upload
3. 然后点击升级，等待路由器重启，亮起绿灯，就完成刷机
4. 重启之后，浏览器进入 10.0.0.1，账号 root，密码 root

**Comment by wujun4code** [comment]
@zhaopengme  你的 uboot 是哪个版本？使用的我提供的 https://github.com/easy-programming-guide/NOKIA-EA0326GMP/blob/main/mt7981-nokia-ea0326gmp-fip-expand.bin 这个么？

**Comment by zhaopengme** [comment]
棒棒，修复了。可以了。谢谢哈
